name: site
description: Felipe Sales | Social Links.
publish_to: 'none'
version: 2.2.2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bloc_test: ^9.1.7
  dio: ^5.6.0
  email_validator: ^3.0.0
  envied: ^0.5.4
  equatable: ^2.0.5
  firebase_analytics: ^11.2.1
  firebase_core: ^3.3.0
  firebase_core_platform_interface: ^5.2.0
  firebase_core_web: ^2.17.4
  firebase_remote_config: ^5.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  g_recaptcha_v3: ^0.0.6
  get_it: ^7.7.0
  intl: ^0.19.0
  lottie: ^3.1.2
  package_info_plus: ^8.0.2
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.3.0
  url_strategy: ^0.3.0

dependency_overrides:
  archive: ^3.6.1

dev_dependencies:
  build_runner: ^2.4.12
  envied_generator: ^0.5.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/components/
    - assets/components/contact/
    - assets/components/experience/
    - assets/components/presentation/
    - assets/components/projects/
    - assets/components/social/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
  generate: true
