name: site
description: Felipe Sales | Social Links.
publish_to: 'none'
version: 2.2.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  dio: ^5.4.3+1
  email_validator: ^2.1.17
  envied: ^0.5.4+1
  equatable: ^2.0.5
  firebase_analytics: ^10.10.6
  firebase_core: ^2.31.1
  firebase_core_platform_interface: ^5.0.0
  firebase_core_web: ^2.17.0
  firebase_remote_config: ^4.4.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  g_recaptcha_v3: ^0.0.6
  get_it: ^7.6.7
  intl: ^0.19.0
  lottie: ^3.1.2
  package_info_plus: ^8.0.0
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.2.6
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.10
  envied_generator: ^0.5.4+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/components/
    - assets/components/contact/
    - assets/components/experience/
    - assets/components/presentation/
    - assets/components/projects/
    - assets/components/social/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
  generate: true
